#!/bin/bash
wget https://hobbitdata.informatik.uni-leipzig.de/NCES2/Datasets.zip -O ./Method/Datasets.zip
wget https://hobbitdata.informatik.uni-leipzig.de/NCES2/pretrained.zip -O ./Method/pretrained.zip
unzip ./Method/Datasets.zip ./Method/pretrained.zip
rm -f ./Method/Datasets.zip ./Method/pretrained.zip
